### ISSUE TITLE
转产分隔线的宽度是多少? Changing the width of the line dividers?

### ISSUE THREAD

**Issue by ahaverty** [baoyachi/StepView#25]
How can I change the width of the line dividers? I want the stepView to match_parent

我怎样才能改变线分隔的宽度是多少？我想 stepView 到 match_parent
谢谢

**Comment by ahaverty** [comment]
The issue was that the stepView was only taking up about half of the device width.
I believe I have fixed this in my fork, let me know if you would like me to clean things up and make a pull request. 

问题是，stepView 只占用了有关设备宽度的一半
我相信，我在我的叉子固定这一点，让我知道如果你要我清理东西，让一拉请求

https://github.com/ahaverty/StepView/commit/718857aef3720481f701efff91cfcab1e251a421

**Comment by ja1984** [comment]
@ahaverty I have the same issue as you, I even tried your fix and it sure works better, but I'm still having some issues. I get at pretty big padding on left side which makes my last two steps really tight.

I looked at your code but can't really figure out what might be wrong. And ideas?
